### PR TITLE
#186510319 : Add Actions support in middleware

### PR DESCRIPTION
**Pull request by selectiveduplicate**
~~Keeping it in draft for now for further testing.~~
~~Going to update the README asap.~~

## Local test results

```sh
MOESIF: [moesifInitiator] start
MOESIF: [ensureValidOptions took time ] 0 seconds
MOESIF: [governance] loading rules
MOESIF: [moesifInitiator] returning moesifMiddleware Function
MOESIF: [moesifInitiator] start
MOESIF: [ensureValidOptions took time ] 0 seconds
MOESIF: [governance] skip loading rules, already loaded recently
MOESIF: [moesifInitiator] returning moesifMiddleware Function


  unit tests for sending actions
MOESIF: [sendAction] convertedActionObject=
{"actionName":"Clicked 'Sign up'","metadata":{"button_label":"Get Started","sign_up_method":"Google SSO"},"request":{"uri":"https://api.acmeinc.com/get-started/","ipAddress":"199.2.232.2"}}
MOESIF: [sendAction] actionModel valid
{"actionName":"Clicked 'Sign up'","metadata":{"button_label":"Get Started","sign_up_method":"Google SSO"},"request":{"uri":"https://api.acmeinc.com/get-started/","ip_address":"199.2.232.2"}}
    ✔ send a single valid action
MOESIF: [sendActionsBatch] convertedActionArray=
[{"transactionId":"7533d9ff-078f-4932-87dc-28e353baf96a","actionName":"Clicked Sign Up","session_token":"23abf0owekfmcn4u3qypxg09w4d8ayrcdx8nu2ng]s98y18cx98q3yhwmnhcfx43f","user_id":964,"company_id":924,"metadata":{"email":"alex@acmeinc.com","button_label":"Get Started","sign_up_method":"Google SSO"},"request":{"time":"2024-11-04T13:26:17.878Z","uri":"https://api.acmeinc.com/items/reviews/","ipAddress":"69.48.220.123","userAgentString":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0"}},{"transactionId":"f4a4d8fc-e681-4367-95ce-36ea110326ec","actionName":"Viewed pricing","session_token":"23jdf0owejfmbn4u3qypxg09w4d8ayrxdx8nu2ng]s98y18cx98q3yhwmnhcfx43f","user_id":382,"company_id":522,"metadata":{"email":"kim@acmeinc.com","button_label":"See pricing","sign_up_method":"Google SSO"},"request":{"time":"2024-11-04T13:26:17.878Z","uri":"https://api.acmeinc.com/pricing/","ipAddress":"61.48.220.126","userAgentString":"PostmanRuntime/7.26.5"}}]
MOESIF: [sendActionsBatch] actionsBatchModel valid
    ✔ send a batch of valid actions
MOESIF: [sendAction] convertedActionObject=
{"actionName":"Clicked 'Sign up'","metadata":{"button_label":"Get Started","sign_up_method":"Google SSO"},"request":{}}
    ✔ throws error when sending a single action with invalid request field
MOESIF: [sendActionsBatch] convertedActionArray=
[{"transactionId":"6c5d0ca5-e078-46ac-bfaa-2d8c9a82cb1e","actionName":"Clicked Sign Up","session_token":"23abf0owekfmcn4u3qypxg09w4d8ayrcdx8nu2ng]s98y18cx98q3yhwmnhcfx43f","user_id":611,"company_id":269,"metadata":{"email":"alex@acmeinc.com","button_label":"Get Started","sign_up_method":"Google SSO"},"request":{"time":1730726777882,"ipAddress":"12.48.120.123"}},{"transactionId":"b37b60a3-b270-453f-94fb-f90d39d99708","actionName":"Viewed pricing","session_token":"23jdf0owejfmbn4u3qypxg09w4d8ayrxdx8nu2ng]s98y18cx98q3yhwmnhcfx43f","user_id":22,"company_id":671,"metadata":{"email":"kim@acmeinc.com","button_label":"See pricing","sign_up_method":"Google SSO"},"request":{"time":1730726777882,"ipAddress":"12.48.220.123"}}]
    ✔ throws error when sending a batch of actions with invalid request field

  unit tests for updating companies or users
{"company_id":"randomId0.20333996685060285","modified_time":null,"ip_address":"199.2.232.2","company_domain":"hello.com","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}
{"company_id":"randomId0.20333996685060285","modified_time":null,"ip_address":"199.2.232.2","company_domain":"hello.com","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}
    ✔ verify toJSON converts camelCase to snake_case for Company predefined fields
MOESIF: [updateCompany] convertedCompany=
{"company_id":"randomId0.6346703109120917","modified_time":null,"ip_address":"199.2.232.2","company_domain":"hello.com","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}
MOESIF: [updateCompany] companyModel valid
{ errorMessage: 'done is not defined', errorCode: undefined }
{ errorMessage: 'done is not defined', errorCode: undefined }
    ✔ update single company (1342ms)
MOESIF: [governance] obtained 10rules
MOESIF: [updateCompany] convertedCompany=
{"company_id":"randomId0.7062638197791822","modified_time":null,"ip_address":"199.2.232.2","company_domain":"hello.com","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}
MOESIF: [updateCompany] companyModel valid
    ✔ update single company promise (578ms)
MOESIF: [updateCompaniesBatch] convertedCompaniesArray=
[{"company_id":"randomId0.9285104251587539","modified_time":null,"ip_address":"199.2.232.2","company_domain":"twitch.com","metadata":{"name":"dude"},"campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}},{"company_id":"randomId0.177262360285249","modified_time":null,"ip_address":"199.2.232.2","company_domain":"stuff.com","metadata":{"name":"stuff"},"campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}]
MOESIF: [updateCompaniesBatch] companiesBatchModel valid
    ✔ update company batch (627ms)
MOESIF: [updateCompaniesBatch] convertedCompaniesArray=
[{"company_id":"randomId0.09760103755941985","modified_time":null,"ip_address":"199.2.232.2","company_domain":"twitch.com","metadata":{"name":"dude"},"campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}},{"company_id":"randomId0.019437455289689876","modified_time":null,"ip_address":"199.2.232.2","company_domain":"stuff.com","metadata":{"name":"stuff"},"campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}]
MOESIF: [updateCompaniesBatch] companiesBatchModel valid
    ✔ update company batch promise (514ms)
MOESIF: [updateUser] convertedUserObject=
{"user_id":"userId0.8895951508187931","company_id":"helloThere","modified_time":null,"ip_address":"199.2.232.2","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}
MOESIF: [updateUser] userModel valid
    ✔ update single user (349ms)
MOESIF: [updateUser] convertedUserObject=
{"user_id":"userId0.9268720196602378","company_id":"helloThere","modified_time":null,"ip_address":"199.2.232.2","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}
MOESIF: [updateUser] userModel valid
    ✔ update single user promise (444ms)
MOESIF: [updateUsersBatch] convertedUserArray=
[{"user_id":"userId0.23824872915819229","company_id":"helloThere","modified_time":null,"ip_address":"199.2.232.2","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}},{"user_id":"userId0.2559037880130539","company_id":"helloThere","modified_time":null,"ip_address":"199.2.232.2","metadata":{"name":"you","first_name":"hello"},"campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}]
MOESIF: [updateUsersBatch] usersBatchModel valid
    ✔ update user batch (579ms)
MOESIF: [updateUsersBatch] convertedUserArray=
[{"user_id":"userId0.7979493966438478","company_id":"helloThere","modified_time":null,"ip_address":"199.2.232.2","campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}},{"user_id":"userId0.7254245525430958","company_id":"helloThere","modified_time":null,"ip_address":"199.2.232.2","metadata":{"name":"you","first_name":"hello"},"campaign":{"utm_source":null,"utm_medium":null,"utm_campaign":null,"utm_term":null,"utm_content":null,"referrer":null,"referring_domain":null,"gclid":null}}]
MOESIF: [updateUsersBatch] usersBatchModel valid
    ✔ update user batch promise (556ms)
MOESIF: [updateSubscription] convertedSubscription=
{"subscription_id":"subscriptionId0.7835149454900874","company_id":"random0.3847484678842332","current_period_start":"2024-09-04T13:26:22.877Z","current_period_end":"2024-11-04T13:26:22.877Z","status":"active","metadata":{"random":"abc"}}
    ✔ update single subscription promise (2244ms)
MOESIF: [updateSubscriptionsBatch] convertedSubscriptionsArray=
[{"subscription_id":"subscriptionId0.09749611565959038","company_id":"random0.18662146725762807","current_period_start":"2024-09-04T13:26:25.120Z","current_period_end":"2024-11-04T13:26:25.120Z","status":"active","metadata":{"random":"abc"}},{"subscription_id":"subscriptionId0.7230762905245545","company_id":"random0.6330402143417799","current_period_start":"2024-08-04T13:26:25.120Z","current_period_end":"2024-12-04T13:26:25.120Z","status":"active","metadata":{"random":"abc2"}}]
    ✔ update batch subscription promise (2342ms)


  15 passing (10s)
```

## Testing with Expresss.js

```javascript
var express = require('express');
var app = express();

var moesif = require('./lib');

const TEST_APPLICATION_ID = '';
const PORT = 3050;

var moesifMiddleWare = moesif({ applicationId: TEST_APPLICATION_ID });

app.use(moesifMiddleWare);
app.use(express.json());

app.get('/', function (req, res) {
  res.json({ a: 'abc' });
});

app.get('/abc', function (req, res) {
  res.json({ abc: 'abcefg' });
});

app.post('/action', function (req, res) {
  var actionModel = req.body;
  moesifMiddleWare.sendAction(actionModel, function (error, res) {
    if (error) {
      console.log(error);
    }
  });
  res.json(req.body);
});

app.post('/actions', function (req, res) {
  var actions = req.body;
  console.log(actions)
  console.log(Array.isArray(actions))
  moesifMiddleWare.sendActionsBatch(actions, function (error, res) {
    if (error) {
      console.log(error);
    }
  });
  res.json(req.body);
});

app.listen(PORT, function () {
  console.log(`Example app listening on port ${PORT}!`);
});
```

Adding a batch of actions:

```json
[
  {
    "actionName":"Clicked Sign Up",
    "user_id":"12345",
    "company_id":"67890",
    "transaction_id":"a3765025-46ec-45dd-bc83-b136c8d1d257",
    "request":{
      "uri":"https://acmeinc.com/pricing",
      "user_agent_string":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
    },
    "metadata":{
      "button_label":"Get Started",
      "sign_up_method":"Google SSO"
    }
  },
  {
    "actionName":"Purchased Subscription",
    "user_id":"12345",
    "company_id":"67890",
    "transaction_id":"a90cbabb-2dfc-4290-a368-48ce1a1af7ba",
    "request":{
      "uri":"https://acmeinc.com/pricing",
      "user_agent_string":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
    },
    "metadata":{
      "plan_name":"Pay As You Go",
      "plan_revenue":5000
    }
  }
]
```

image

### CODE REVIEW

**Comment by praves77** [comment]
@selectiveduplicate it looks fine to me. What is `moesif-nodejs-3.10.6.tgz` file for? Added by mistake?

**Comment by selectiveduplicate** [comment]
@praves77 Yeah sorry it's added by mistake at some point while I was testing another nodejs app with a local version of the nodejs middleware using `npm pack`. :sweat_smile:

**Comment by praves77** [comment]
@selectiveduplicate do you want to remove it then we can approve/merge/publish?

**Comment by selectiveduplicate** [comment]
> @selectiveduplicate do you want to remove it then we can approve/merge/publish?

@praves77 It should be removed afact; I see it in "Files Changed" in red mark as in removed.

**Review by praves77 — APPROVED** [review]

**Pull request merged**
